# Generated by Django 5.2 on 2025-04-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='LittleLemon_price_e9107e_idx',
        ),
    ]
