# Generated by Django 5.2 on 2025-04-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='author',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='inventory',
            field=models.SmallIntegerField(),
        ),
    ]
